name: Build and Push Docker image

on:
  push:
    branches:
      - main  # プッシュするブランチを指定（例: main）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker tag mariadb:latest ghcr.io/retdayo/pterodactyl-mariadb-egg/mariadb:latest

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository }}/mariadb:latest
